[project]
authors = ["Cameron Carstens"]
entry = "main.sw"
license = "Apache-2.0"
name = "test_asset_id"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.4.4" }
